
title: Modular Devices / Malleable Audio
email: info.malleable@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We make modular devices for audio creation, processing, and control, creating 
  malleable audio from modular devices. 
baseurl: "" # site is served from the root, not a /project subpath
url: https://modulardevicesmalleableaudio.github.io # the base hostname & protocol for your site
domain: modulardevicesmalleableaudio.github.io # no http forces https
twitter_username: malleable808
github_username:  ModularDevicesMalleableAudio

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-feed

footer: mdma
header_pages:
  - index.md
  - about.md
  - projects.md
  - documentation.md
  - repos.md